GET http://localhost:4000/

###

POST http://localhost:4000/
content-type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}


###
PUT http://localhost:4000/
content-type: application/json

{
    "title": "final title"
}
